// <auto-generated />
namespace Study2019.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_navProperty_to_posts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_navProperty_to_posts));
        
        string IMigrationMetadata.Id
        {
            get { return "202001291609495_add_navProperty_to_posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
